"""
Cell-grid texture filter — blue-noise neighbour invasion.

Slot in the pixelate / circulate pipelines AFTER the palette-snap step:
takes a palette-snapped `(cells_y, cells_x, 3)` uint8 RGB grid and
sporadically replaces "deep-interior" cells (cells surrounded by their
own colour) with the locally-dominant neighbouring colour. The result
breaks up large monochromatic islands without touching boundary cells
(which are already visually varied).

The decision per cell is deterministic and stateless:

  threshold(cy, cx) = LUT[cy mod 256, cx mod 256] / 255
  interior_score(cy, cx) = (# Moore-1 neighbours sharing me's colour) / 8
  → replace if threshold < strength · interior_score³

The threshold comes from a precomputed 256×256 blue-noise LUT (committed
binary, generated by `scripts/build-blue-noise-lut.py`). Blue-noise
distributes the replacements organically — no banding, no clusters.

The replacement colour is the most common neighbour palette index in the
Moore-radius-2 (5×5) window, excluding `me`. Ties are broken in
iteration order (dy in -2..2, dx in -2..2). Both rules are mirrored
exactly in `lib/editor/trace/cell-texture.ts`; a parity test guards
byte-equivalence (see `tests/test_cell_texture.py` +
`lib/editor/trace/cell-texture.test.ts`).

`strength = 0` (or `texture_enabled = false` upstream) is a no-op: no
LUT access, no neighbour scan, the input array is returned verbatim.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np

# Blue-noise LUT, loaded once at import. Shape (256, 256) uint8. The same
# binary is served to the browser via `public/assets/blue-noise-256.bin`
# so client previews use byte-identical thresholds.
_LUT_PATH = Path(__file__).parent / "data" / "blue_noise_256.bin"
BLUE_NOISE_LUT: np.ndarray = np.fromfile(_LUT_PATH, dtype=np.uint8).reshape(256, 256)

# Algorithm constants. Same values in the TS mirror.
_INTERIOR_ALPHA = 3  # exponent on interior_score in the threshold check
_INVASION_RADIUS = 2  # Moore-radius for the neighbour-mode lookup (5×5)


def _reconstruct_palette_idx(
    cells_rgb: np.ndarray, palette_rgb: np.ndarray
) -> np.ndarray:
    """Map each cell's RGB triple to its palette index. The cells are
    palette-snapped, so every cell colour equals exactly one palette
    chip — a packed-uint32 hash makes the lookup O(N + M)."""
    cells = np.asarray(cells_rgb, dtype=np.uint8)
    palette = np.asarray(palette_rgb, dtype=np.uint8)

    def pack(arr: np.ndarray) -> np.ndarray:
        # Pack (..., 3) uint8 → (...) uint32 by laying out R, G, B in the
        # low bytes. Safe because each channel ≤ 255.
        a32 = arr.astype(np.uint32)
        return (a32[..., 0] << 16) | (a32[..., 1] << 8) | a32[..., 2]

    cell_keys = pack(cells).ravel()
    pal_keys = pack(palette)

    # `searchsorted` on a sorted palette gives the index; we sort the
    # palette here, look up, and translate back through the inverse perm.
    order = np.argsort(pal_keys)
    sorted_keys = pal_keys[order]
    pos = np.searchsorted(sorted_keys, cell_keys)
    # `pos` may equal len(sorted_keys) when a cell colour isn't in the
    # palette (shouldn't happen post-snap, but guard against it). Clip and
    # validate.
    pos = np.clip(pos, 0, len(sorted_keys) - 1)
    matched = sorted_keys[pos] == cell_keys
    if not matched.all():
        raise ValueError(
            "apply_neighbor_invasion: cells_rgb contains colours not in palette_rgb"
        )
    idx_flat = order[pos]
    return idx_flat.reshape(cells.shape[:2]).astype(np.int32)


def apply_neighbor_invasion(
    cells_rgb: np.ndarray,
    palette_rgb: np.ndarray,
    strength: float,
) -> np.ndarray:
    """Apply the blue-noise neighbour-invasion texture step.

    Parameters
    ----------
    cells_rgb : ndarray (cells_y, cells_x, 3) uint8
        Palette-snapped per-cell RGB. Returned as-is when `strength <= 0`.
    palette_rgb : ndarray (M, 3) uint8
        Active palette (Munsell or grays) — the cells were snapped to it.
    strength : float
        0..1; the maximum probability of replacement for a fully interior
        cell (interior_score = 1). Below 0 is treated as 0.

    Returns
    -------
    ndarray (cells_y, cells_x, 3) uint8
        New array (input is not mutated). Every cell colour is still a
        palette chip — the replacement always comes from `palette_rgb`.
    """
    if strength <= 0.0:
        return np.asarray(cells_rgb, dtype=np.uint8).copy()

    cells_rgb = np.asarray(cells_rgb, dtype=np.uint8)
    palette_rgb = np.asarray(palette_rgb, dtype=np.uint8)
    if cells_rgb.ndim != 3 or cells_rgb.shape[2] != 3:
        raise ValueError("cells_rgb must have shape (H, W, 3)")
    if palette_rgb.ndim != 2 or palette_rgb.shape[1] != 3:
        raise ValueError("palette_rgb must have shape (M, 3)")

    H, W = cells_rgb.shape[:2]
    palette_idx = _reconstruct_palette_idx(cells_rgb, palette_rgb)
    out = cells_rgb.copy()
    lut = BLUE_NOISE_LUT
    r_inv = _INVASION_RADIUS

    for cy in range(H):
        for cx in range(W):
            me = int(palette_idx[cy, cx])

            # Moore-1 same-colour count (skip OOB; never divide by less
            # than 8 — boundaries have a lower interior_score by design).
            same = 0
            for dy in (-1, 0, 1):
                ny = cy + dy
                if ny < 0 or ny >= H:
                    continue
                for dx in (-1, 0, 1):
                    if dy == 0 and dx == 0:
                        continue
                    nx = cx + dx
                    if nx < 0 or nx >= W:
                        continue
                    if int(palette_idx[ny, nx]) == me:
                        same += 1
            interior_score = same / 8.0
            threshold = lut[cy % 256, cx % 256] / 255.0
            if threshold >= strength * (interior_score ** _INTERIOR_ALPHA):
                continue

            # Mode of differing palette indices in the Moore-r=2 window.
            # Iteration order (dy then dx) defines tie-breaks — mirrored in TS.
            counts: dict[int, int] = {}
            for dy in range(-r_inv, r_inv + 1):
                ny = cy + dy
                if ny < 0 or ny >= H:
                    continue
                for dx in range(-r_inv, r_inv + 1):
                    if dy == 0 and dx == 0:
                        continue
                    nx = cx + dx
                    if nx < 0 or nx >= W:
                        continue
                    nidx = int(palette_idx[ny, nx])
                    if nidx == me:
                        continue
                    counts[nidx] = counts.get(nidx, 0) + 1
            if not counts:
                continue
            # Strict `>` so the FIRST key with the max count wins (dict
            # iteration is insertion order on CPython 3.7+; the TS mirror
            # uses a Map which is also insertion-ordered).
            invading_idx = -1
            best = 0
            for k, v in counts.items():
                if v > best:
                    best = v
                    invading_idx = k
            out[cy, cx] = palette_rgb[invading_idx]

    return out
