-- @intent-data-migration
--
-- Add iscc_nbs_name to lab_munsell + lab_grays, seeded by mapping
-- each chip's Munsell HVC coordinates to the corresponding
-- ISCC-NBS Level-3 block name (267 named regions in Munsell color
-- space — NBS Special Publication 440, Kelly & Judd).
--
-- Source data: color-lab/source/iscc-nbs.xml (CC0-1.0). Generated
-- by scripts/build-iscc-nbs-seed.mjs — do not hand-edit; re-run
-- the loader to regenerate.

ALTER TABLE "public"."lab_munsell" ADD COLUMN IF NOT EXISTS "iscc_nbs_name" text;
ALTER TABLE "public"."lab_grays"    ADD COLUMN IF NOT EXISTS "iscc_nbs_name" text;

-- Per-chip UPDATEs (idempotent; matched by unique notation).
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Dark red' WHERE "notation" = '2.5R 2.5/8';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Vivid red' WHERE "notation" = '2.5R 4.5/16';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Vivid pink' WHERE "notation" = '2.5R 6.5/12';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Light pink' WHERE "notation" = '2.5R 8.5/4';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Strong red' WHERE "notation" = '5R 3.5/12';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Vivid red' WHERE "notation" = '5R 5.5/16';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Light pink' WHERE "notation" = '5R 8.5/4';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Deep reddish orange' WHERE "notation" = '7.5R 3.5/12';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Vivid reddish orange' WHERE "notation" = '7.5R 5.5/16';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Moderate yellowish pink' WHERE "notation" = '7.5R 7.5/6';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Strong reddish brown' WHERE "notation" = '10R 2.5/10';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Vivid reddish orange' WHERE "notation" = '10R 5.5/14';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Strong yellowish pink' WHERE "notation" = '10R 7.5/8';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Strong brown' WHERE "notation" = '2.5YR 2.5/8';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Deep orange' WHERE "notation" = '2.5YR 4.5/10';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Vivid orange' WHERE "notation" = '2.5YR 6.5/14';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Strong brown' WHERE "notation" = '5YR 2.5/6';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Deep orange' WHERE "notation" = '5YR 4.5/10';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Strong orange' WHERE "notation" = '5YR 6.5/12';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Light yellowish pink' WHERE "notation" = '5YR 8.5/4';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Strong brown' WHERE "notation" = '7.5YR 3.5/6';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Deep orange yellow' WHERE "notation" = '7.5YR 5.5/10';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Pale orange yellow' WHERE "notation" = '7.5YR 8.5/4';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Strong yellowish brown' WHERE "notation" = '10YR 3.5/6';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Dark orange yellow' WHERE "notation" = '10YR 5.5/8';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Strong orange yellow' WHERE "notation" = '10YR 7.5/12';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Moderate olive brown' WHERE "notation" = '2.5Y 2.5/4';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Deep yellow' WHERE "notation" = '2.5Y 5.5/8';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Strong yellow' WHERE "notation" = '2.5Y 7.5/10';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Moderate olive' WHERE "notation" = '5Y 2.5/4';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Light olive' WHERE "notation" = '5Y 4.5/6';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Strong yellow' WHERE "notation" = '5Y 6.5/8';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Moderate olive' WHERE "notation" = '7.5Y 2.5/4';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Light olive' WHERE "notation" = '7.5Y 4.5/6';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Strong greenish yellow' WHERE "notation" = '7.5Y 6.5/8';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Brilliant greenish yellow' WHERE "notation" = '7.5Y 8.5/10';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Moderate olive' WHERE "notation" = '10Y 3.5/4';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Deep greenish yellow' WHERE "notation" = '10Y 5.5/8';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Brilliant greenish yellow' WHERE "notation" = '10Y 8.5/10';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Moderate olive green' WHERE "notation" = '2.5GY 3.5/6';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Strong yellow green' WHERE "notation" = '2.5GY 5.5/8';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Brilliant yellow green' WHERE "notation" = '2.5GY 7.5/10';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Moderate olive green' WHERE "notation" = '5GY 2.5/4';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Strong yellow green' WHERE "notation" = '5GY 5.5/8';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Brilliant yellow green' WHERE "notation" = '5GY 7.5/10';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Moderate olive green' WHERE "notation" = '7.5GY 2.5/6';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Strong yellow green' WHERE "notation" = '7.5GY 4.5/8';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Vivid yellow green' WHERE "notation" = '7.5GY 6.5/12';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Dark yellowish green' WHERE "notation" = '10GY 2.5/6';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Strong yellowish green' WHERE "notation" = '10GY 4.5/10';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Vivid yellowish green' WHERE "notation" = '10GY 6.5/14';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Vivid yellowish green' WHERE "notation" = '10GY 8.5/16';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Dark yellowish green' WHERE "notation" = '2.5G 3.5/6';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Strong yellowish green' WHERE "notation" = '2.5G 5.5/8';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Vivid yellowish green' WHERE "notation" = '2.5G 8.5/12';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Moderate green' WHERE "notation" = '5G 3.5/6';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Brilliant green' WHERE "notation" = '5G 5.5/8';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Brilliant green' WHERE "notation" = '5G 7.5/10';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Dark green' WHERE "notation" = '7.5G 2.5/4';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Light green' WHERE "notation" = '7.5G 5.5/6';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Brilliant green' WHERE "notation" = '7.5G 7.5/10';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Dark bluish green' WHERE "notation" = '10G 2.5/4';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Moderate bluish green' WHERE "notation" = '10G 4.5/6';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Brilliant bluish green' WHERE "notation" = '10G 6.5/8';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Dark bluish green' WHERE "notation" = '2.5BG 2.5/4';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Moderate bluish green' WHERE "notation" = '2.5BG 4.5/6';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Brilliant bluish green' WHERE "notation" = '2.5BG 6.5/8';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Brilliant bluish green' WHERE "notation" = '2.5BG 8.5/8';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Moderate bluish green' WHERE "notation" = '5BG 3.5/4';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Light bluish green' WHERE "notation" = '5BG 5.5/6';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Brilliant bluish green' WHERE "notation" = '5BG 8.5/8';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Moderate bluish green' WHERE "notation" = '7.5BG 3.5/4';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Light bluish green' WHERE "notation" = '7.5BG 5.5/6';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Brilliant bluish green' WHERE "notation" = '7.5BG 7.5/8';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Dark grayish blue' WHERE "notation" = '10BG 2.5/2';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Light greenish blue' WHERE "notation" = '10BG 5.5/6';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Brilliant greenish blue' WHERE "notation" = '10BG 7.5/8';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Dark grayish blue' WHERE "notation" = '2.5B 2.5/2';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Moderate greenish blue' WHERE "notation" = '2.5B 4.5/4';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Light greenish blue' WHERE "notation" = '2.5B 6.5/6';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Dark greenish blue' WHERE "notation" = '5B 2.5/4';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Moderate greenish blue' WHERE "notation" = '5B 4.5/6';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Brilliant greenish blue' WHERE "notation" = '5B 6.5/8';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Very light greenish blue' WHERE "notation" = '5B 8.5/6';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Moderate greenish blue' WHERE "notation" = '7.5B 3.5/4';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Brilliant greenish blue' WHERE "notation" = '7.5B 5.5/8';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Very light greenish blue' WHERE "notation" = '7.5B 8.5/6';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Moderate blue' WHERE "notation" = '10B 3.5/6';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Light blue' WHERE "notation" = '10B 5.5/8';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Very light blue' WHERE "notation" = '10B 7.5/8';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Dark blue' WHERE "notation" = '2.5PB 2.5/6';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Brilliant blue' WHERE "notation" = '2.5PB 5.5/10';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Very light blue' WHERE "notation" = '2.5PB 7.5/8';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Dark blue' WHERE "notation" = '5PB 2.5/6';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Strong blue' WHERE "notation" = '5PB 4.5/12';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Brilliant blue' WHERE "notation" = '5PB 6.5/12';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Vivid purplish blue' WHERE "notation" = '7.5PB 2.5/16';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Vivid purplish blue' WHERE "notation" = '7.5PB 4.5/16';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Brilliant purplish blue' WHERE "notation" = '7.5PB 6.5/12';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Very pale purplish blue' WHERE "notation" = '7.5PB 8.5/4';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Vivid violet' WHERE "notation" = '10PB 3.5/16';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Vivid violet' WHERE "notation" = '10PB 5.5/16';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Very pale violet' WHERE "notation" = '10PB 8.5/4';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Vivid violet' WHERE "notation" = '2.5P 3.5/16';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Vivid violet' WHERE "notation" = '2.5P 5.5/16';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Brilliant violet' WHERE "notation" = '2.5P 7.5/10';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Vivid purple' WHERE "notation" = '5P 2.5/14';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Vivid purple' WHERE "notation" = '5P 5.5/16';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Brilliant purple' WHERE "notation" = '5P 7.5/10';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Deep purple' WHERE "notation" = '7.5P 2.5/12';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Vivid purple' WHERE "notation" = '7.5P 4.5/16';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Vivid purple' WHERE "notation" = '7.5P 6.5/16';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Deep reddish purple' WHERE "notation" = '10P 2.5/12';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Vivid reddish purple' WHERE "notation" = '10P 4.5/16';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Strong purplish pink' WHERE "notation" = '10P 6.5/16';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Light purplish pink' WHERE "notation" = '10P 8.5/6';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Vivid reddish purple' WHERE "notation" = '2.5RP 3.5/14';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Vivid reddish purple' WHERE "notation" = '2.5RP 5.5/16';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Light purplish pink' WHERE "notation" = '2.5RP 8.5/6';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Strong purplish red' WHERE "notation" = '5RP 3.5/12';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Vivid purplish red' WHERE "notation" = '5RP 5.5/16';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Light purplish pink' WHERE "notation" = '5RP 7.5/8';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Deep purplish red' WHERE "notation" = '7.5RP 2.5/10';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Vivid purplish red' WHERE "notation" = '7.5RP 5.5/16';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Light purplish pink' WHERE "notation" = '7.5RP 7.5/8';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Deep purplish red' WHERE "notation" = '10RP 2.5/10';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Vivid purplish red' WHERE "notation" = '10RP 4.5/16';
UPDATE "public"."lab_munsell" SET "iscc_nbs_name" = 'Vivid pink' WHERE "notation" = '10RP 6.5/12';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Black' WHERE "notation" = 'N 0.00/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Black' WHERE "notation" = 'N 0.21/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Black' WHERE "notation" = 'N 0.43/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Black' WHERE "notation" = 'N 0.64/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Black' WHERE "notation" = 'N 0.85/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Black' WHERE "notation" = 'N 1.06/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Black' WHERE "notation" = 'N 1.28/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Black' WHERE "notation" = 'N 1.49/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Black' WHERE "notation" = 'N 1.70/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Black' WHERE "notation" = 'N 1.91/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Black' WHERE "notation" = 'N 2.13/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Black' WHERE "notation" = 'N 2.34/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Dark gray' WHERE "notation" = 'N 2.55/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Dark gray' WHERE "notation" = 'N 2.77/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Dark gray' WHERE "notation" = 'N 2.98/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Dark gray' WHERE "notation" = 'N 3.19/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Dark gray' WHERE "notation" = 'N 3.40/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Dark gray' WHERE "notation" = 'N 3.62/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Dark gray' WHERE "notation" = 'N 3.83/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Dark gray' WHERE "notation" = 'N 4.04/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Dark gray' WHERE "notation" = 'N 4.26/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Dark gray' WHERE "notation" = 'N 4.47/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Medium gray' WHERE "notation" = 'N 4.68/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Medium gray' WHERE "notation" = 'N 4.89/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Medium gray' WHERE "notation" = 'N 5.11/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Medium gray' WHERE "notation" = 'N 5.32/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Medium gray' WHERE "notation" = 'N 5.53/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Medium gray' WHERE "notation" = 'N 5.74/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Medium gray' WHERE "notation" = 'N 5.96/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Medium gray' WHERE "notation" = 'N 6.17/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Medium gray' WHERE "notation" = 'N 6.38/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Light gray' WHERE "notation" = 'N 6.60/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Light gray' WHERE "notation" = 'N 6.81/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Light gray' WHERE "notation" = 'N 7.02/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Light gray' WHERE "notation" = 'N 7.23/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Light gray' WHERE "notation" = 'N 7.45/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Light gray' WHERE "notation" = 'N 7.66/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Light gray' WHERE "notation" = 'N 7.87/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Light gray' WHERE "notation" = 'N 8.09/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'Light gray' WHERE "notation" = 'N 8.30/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'White' WHERE "notation" = 'N 8.51/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'White' WHERE "notation" = 'N 8.72/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'White' WHERE "notation" = 'N 8.94/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'White' WHERE "notation" = 'N 9.15/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'White' WHERE "notation" = 'N 9.36/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'White' WHERE "notation" = 'N 9.57/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'White' WHERE "notation" = 'N 9.79/';
UPDATE "public"."lab_grays"   SET "iscc_nbs_name" = 'White' WHERE "notation" = 'N 10.00/';
